### ISSUE TITLE
Wato-GUI Slave-ID Parameter 

### ISSUE THREAD

**Issue by Maxheino** [vtacquet/agent_modbus#1]
Hello,
Is it possible to define the Modbus slave ID via the Wato Gui?

Best regards
Erwin
![grafik](https://github.com/vtacquet/agent_modbus/assets/64358594/04b12f6f-34ef-4936-82b3-9a3bfe6eb842)

**Comment by vtacquet** [comment]
Can't help you there, I only created the cli agent, not the interface in Wato

**Comment by KoMa1978** [comment]
Have a look at:

[Check MK Forum](https://forum.checkmk.com/t/check-agent-for-modbus/28527/37)
[Github](https://github.com/wjs67/check_mk_plugins/tree/main)
