### ISSUE TITLE
V2 is not printing "header line"

### ISSUE THREAD

**Issue by KoMa1978** [vtacquet/agent_modbus#2]
Hi,

I'm testing with v2 of the agent_modbus and it is working fine with a slave ID.
But in my tests v1 prints "<<<modbus_value>>>\n" and then the values in the next line.

v2 is not printing the line "<<<modbus_value>>>\n".
I assume this is because of the "if (args == 3)" which is set to 4 in line 52.
I the agent version 1.0 this variable is set to "3".
Can someone please check?

Thanks a lot,

**Comment by KoMa1978** [comment]
Any update on this one? Should be easy to fix and would be great to have the old output back.

**Comment by vtacquet** [comment]
this is a sleeping project, but I fixed it for you, since the source code is available you could have fixed it yourself too.

**Comment by KoMa1978** [comment]
Wasn't aware that it is stale ... thanks a lot for the modification and yes in the meanwhile I did the same ;-)
Thanks!
